git submodule add https://github.com/ytdl-org/youtube-dl ./30/youtube-dl
git submodule add https://github.com/meta-introspector/https-lablab.ai-event-audiocraft-24-hours-hackathon/ ./30/https-lablab.ai-event-audiocraft-24-hours-hackathon
git submodule add https://github.com/meta-introspector/audiocraft ./30/audiocraft
git submodule add https://github.com/meta-introspector/encodec ./30/encodec
git submodule add https://github.com/huggingface/transformers.git ./30/encodec/.venv/src/transformers
git submodule add https://github.com/marziabil/emojis ./30/emojis
git submodule add https://github.com/srmalins/primelists ./24/primelists
git submodule add https://github.com/chanyou/python-mock-pb-generator ./29/python-mock-pb-generator
git submodule add https://github.com/audreyfeldroy/cookiecutter-pypackage.git ./12/cookiecutter-pypackage
git submodule add https://github.com/meta-introspector/generators ./12/metameme
git submodule add https://github.com/github/rest-api-description ./19/rest-api-description
git submodule add https://github.com/meta-introspector/meta-meme.wiki.git ./19/meta-meme.wiki
git submodule add https://github.com/Clarifai/clarifai-python ./26/clarifai-python
git submodule add https://github.com/Clarifai/module-prompting ./26/module-prompting
git submodule add https://github.com/AntonOsika/gpt-engineer ./20/gpt-engineer
git submodule add https://github.com/TransformerOptimus/SuperAGI.git ./20/SuperAGI
git submodule add https://github.com/meta-introspector/meta-meme ./20/meta-meme
git submodule add https://github.com/liskovich/ricai_superagi_instance ./25/ricai_superagi_instance
git submodule add https://github.com/jmikedupont2/clarifai-python ./25/clarifai-python
git submodule add ./25/https-lablab.ai-event-llama-2-hackathon-with-clarifai-introspector/vendor/clarifai
git submodule add ./25/https-lablab.ai-event-llama-2-hackathon-with-clarifai-introspector/data
git submodule add https://github.com/jmikedupont2/clarifai-python/ ./25/https-lablab.ai-event-llama-2-hackathon-with-clarifai-introspector
git submodule add https://github.com/liskovich/ricai_codestore_tool ./25/ricai_codestore_tool
git submodule add https://github.com/liskovich/ricai_unittestgen_tool/ ./25/ricai_unittestgen_tool
git submodule add https://github.com/liskovich/CV_generator ./25/CV_generator
git submodule add https://github.com/meta-introspector/https-lablab.ai-event-stablecode-24-hours-hackathon ./25/hackathon
git submodule add https://github.com/wongco/django-imagely ./25/django-imagely
git submodule add https://github.com/irfanakram994/stablecodetutor ./25/stablecodetutor
git submodule add https://github.com/SimFG/to-chatgpt ./01/to-chatgpt
git submodule add https://github.com/ParisNeo/lollms/ ./02/lollms
git submodule add https://github.com/LostRuins/koboldcpp ./02/koboldcpp
git submodule add https://github.com/ParisNeo/lollms-webui ./02/lollms-webui
git submodule add https://github.com/meta-introspector/lollms_bindings_zoo.git ./02/ggml-data/bindings_zoo
git submodule add https://github.com/ParisNeo/lollms_personalities_zoo ./02/ggml-data/personalities_zoo
git submodule add https://github.com/ParisNeo/lollms_extensions_zoo.git ./02/ggml-data/extensions_zoo_path
git submodule add https://github.com/meta-introspector/ggml ./02/ggml-data
git submodule add https://github.com/marella/ctransformers ./02/ctransformers
git submodule add https://github.com/AndreasFischer1985/code-snippets/ ./02/code-snippets
git submodule add https://github.com/fullstorydev/grpcurl ./27/grpcurl
git submodule add https://github.com/caneroj1/clarifai-hs ./27/clarifai-hs
git submodule add https://github.com/Clarifai/clarifai-go-grpc ./27/clarifai-go-grpc
git submodule add https://github.com/googleapis/googleapis ./27/clarifai-nodejs-grpc
git submodule add https://github.com/Clarifai/clarifai-python-grpc ./27/clarifai-python-grpc
git submodule add https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks ./22/Auto-GPT-Benchmarks
git submodule add https://github.com/Azure/aztfexport ./21/aztfexport
git submodule add https://github.com/pyenv/pyenv ./21/pyenv
git submodule add https://github.com/meta-introspector/azure-cli ./21/azure-cli
git submodule add https://github.com/GoogleCloudPlatform/terraformer ./21/terraformer
git submodule add https://github.com/waylaidwanderer/node-chatgpt-api ./21/node-chatgpt-api
