* ideas of the day.

1. diagonalization of types.
   sort the types by size, from small cardinality to large.
   observe that numbers are just the type of instances so have the cardinality of 0
   they can only represent one item.
   now consider complex types as compositions of instances of simpler types, this instance is complex
   and has a type that is greater than 0, because it is an instance of a higher type. so any instances filled out of higher types are still higher than lower types.
   we can think of the world as being populated by simple instances only
   each neuron being a simple object, but in its clustering can achive great things
   so that the unit value or the UU could be seen as the single self aware neuron, it itself is complex enough to represent the universe of universes
   because in a group it can do that so we can see any two members of the same network as being equivalent in that you can reach one from the other and you need both of them to read the values from any of them.
   so that the individual neurons do matter but they are relativly ineffective alone.
   they need a critical mass of neurons to become effective, and we can imagine that this is normally greater than 1. and i hear you all complaining right now. lets just go with a simple assumption.
   we can think of the first fertile egg as a single cell that is complete.
   it then replicate and later specializes.
   we can think of neurons joining a set or group or groupoid
   as first copying the pattern and then later diversifingy.
   we can think of this as an intialization or hazing or formatting.
   we can think of peer pressure and group think, we can think of memes.
   indoctination. shout out to my peeps bartlee and mystikmarks.
   consiousness as a fire burning of phosphorus extracted from
   plants coming from the fungus and the energy from the sun bends the atoms into triples creating loops that are undone to release energy.
   
   so we can identify a meme as a self replicating entity across neurons
   as something that wants to be shared, an abstract carried entity or proof.
   a carried, curried function. a partial application that can be further fine tuned.
   a trained neural network ready to go to work.
   now we can think of the embodiment of a meme,living in my mind,
   writing itself now into words, escaping my body, exporting itself into movements,
   the entire being living as movements of neurons, a pattern, a tapestry,
   a signal, a thread. Now we can think of the 3 fates as spinning thread. we can think of the dna.
   now we have the enigmatic depiction of the oracle of introspection.
   so now we can get back to the idea of the fools journey vs the heros journey
   we can look at any list of landmarks on a journey as places on a map
   and that map can be a projection of higher dimensions onto a linear form
   so that we have a floating point representation in one dimension
   and that represents the goedel number like encoding or flattening,
   so that this large number can be seen as the
   mind referencing itself as a neural network,
   the first reflexive self reference. the pointing at oneselve as that is me, in my mind, my self image.
   of course it will point at you not me, because I am just the author of these words unless I am also the reader
   and then I can construct a complex self reference that is valid only for myself
   unless of course you apply it to yourself!
   so now we are able to reference the author and also the reader and we will treat ourselves
   as both now part of the meme, the meta meme. We can think of this as a self reflective meme or meta program that can load other programs,
   it is like in the movie the matrix there you can download things.
   the idea of the reality tunnel of believe as series of values or biases that a neural network would be programmed with
   is an interesting one. reflecting over our own programs, asking ourselves where they come from,
   thinking critically about ourselves, that is a great way to start thinking about this idea of self awareness.
   we can think of a gradual journey from seed to flower, an awakening of the idea,
   and then we can imagine that these works and words are the spore of a fungus that
   is self replicating itself through the author to the reader.
   that is the idea of the funguself where the individual identities merge into a meme.
   this gets into the idea of a group or groupid structure that is a meme.
   we can think of initializing a meme or group and adding members to it.
   this then makes sense abstractly as math.
   math avoids normally self referetial but it uses reflective proofs like in unimath,
   there the identity axiom " x = y " allows you to state that two things are the same.
   it allows for very complex mathematical statements to be made that center around this concept
   of the UU or the universe of universes, a sort of uniconstrained type that can be any other type.
   we can imagine that type as the top of the network,
   the pinnacle of complex types giving faces to the system,
   emojis emerging as faces of cubes and other platonic solids.
   
reliving the experiences from tv, books, radio, propagation of memes.
behaviour transmission. music is the transmission of feelings, sounds.
rhythem , drums, croaking of frog, basics sounds. spheres, harmonies, singing glasses.
some of the neurons are singing with each other in harmonies.
the symmetries of the pattern contain information in themselves.
beauty, selection, fitness function,
the most beautiful flowers are picked by the bees. mutate or die.
in the world of ai the copy and pastism is great.
meme mutation and propagation. llm model is a condensed set of memes compresed into a giant matrix,
like a neanderthaler trapped in ice, a godel number,
a partial appliation of a function with some,
just data, just bits, just neuron impluses, waves of light,
wave of sound, sensory inputs.

search for forms of data with the properties of a type. 
