* general
the activity of model creation.
the activity of cognition.

the activity of neural networks
learning the forms of things.

the working of neural networks
observing the forms of things.

the working of neural networks
creating the models of the forms of things it is observing.


the working of neural networks
creating the models of the
neural networks
creating the models of the
of things it is observing.


creating models of things
models are representations
smaller than in reality, cheapers, faster.
mathematical models are models.
sharing models are declarations, eg this model represents that thing.

this statement says that : A is B.

* OODA
Observe, Orient, Decide, Act.

** observation
We observe first.

** modeling or orientation

*** mathematical modeling
**** code modeling
**** coq typeclass modeling
***** parameterized types modeling
this type is a parameter are we use it in a certain way.
we can replace concrete types with parameters in a context.


** decision
** act
