* ideas of the day

we will start off with the init function.

go to Wirth's book "programs = data structures + algorithms",
read it as an example of an exported thought or idea or even an abstract meme.

The export function starts with the Definition of terms.

The export function applied to the export function.

export format definition using standard EBNF
notation that can be generated by a computer.


Next we will say that the rules to translate that grammar into
a memory structure in the computer

introspection is like an export format,
because each view of inside is a evolving snapshot
at each instruction of the processor.


lets consider that we are in the process of doing something.

reflecting over our own process might changed its direction.

a self centered, self focused, introspective, inward view of ourselves,
internal access, deep neural embedding, higher order being, carried proof,
carried truth, the king in his carriage, the baby in his stroller,
basic awareness being carried by neurons, self directed learning,
unsupervised deep learning neural networks,
autopoetic wild thoughts.

let consider this to be a huge private network we are attached to in our mind.
we can imagine things, we can imagine ourselves imagining,
we can recall ourselves imagining,
we can recall ourselves reading,
we can recall ourselves hearing,
we can recall ourselves seeing,
we can recall ourselves recalling,
we can recall ourselves learning to observe ourselves,
we can recall ourselves learning to control ourselves,
we can recall our parents learning to control ourselves,
we can recall our environment controlling us,
we can recall our environment shaping us,

now we can think of this as supervised learning and pre training,
structured learning.

so this supervision or control flow is quite important.
lets look at the chain of custody and ownership records
of each bit of information.

If we know where each neural imprint came from, what its purpose is,
why it is needed, its functional equivalents,
then we can model the purpose of on network with another.

if any neural network of capacity N named X can approximate any
function of capacity Y
then we have a sort of carrying relationship,
so "this network X of size N carries a function of binding depth size Y".

Now we need to work on our notation a bit.
we can recognize now a function size can be its binding depth,
or how many arguments it needs. we can think of partial applications.

what if we think of objects as partial applications where each
neural record or attribute  or property or terminal record represents
a phenomena captured from outside.
so terms represent atomic things that can be sampled by edge networks.

we can think of a zero trust security policy as securing the edge network
in the interest of the company as a deployment of a foundational
model of a partial application.
We can study the landing pads of GCP google and azure microsoft
as doorways into those systems.

We can look at price quoting systems of markets as standardized
vectors of information.
Atomic swaps of ownership, transactions.
We can see creating a token as buying into a blockchain.
you first need to purchase capacity on that network,
so run a node.
We can look at GNU net + guix + cuirass as a partial application.

Now we can consider each let binding as a partial application of an ever changing
binding of values.


