git submodule add https://github.com/emacs-lsp/lsp-haskell ./15/lsp-haskell
git submodule add https://github.com/ndmitchell/hlint ./15/hlint
git submodule add https://github.com/pepeiborra/ekg-json ./15/haskell-language-server/dist-newstyle/src/ekg-json-22461580dac5d569
git submodule add https://github.com/haskell/haskell-language-server ./15/haskell-language-server
git submodule add https://github.com/meta-introspector/meta-meme ./30/meta-meme
git submodule add https://github.com/fossas/fossa-cli ./13/fossa-cli
git submodule add https://github.com/fused-effects/fused-effects-parser ./13/fused-effects-parser
git submodule add https://github.com/github/semantic ./13/semantic
git submodule add https://github.com/fused-effects/fused-effects ./13/fused-effects
git submodule add https://github.com/fused-effects/fused-effects-lens ./13/fused-effects-lens
git submodule add https://github.com/ghc/ghc.git ./05/ghc
git submodule add https://github.com/haskell/happy.git ./05/happy
git submodule add https://github.com/scotty-web/scotty ./24/scotty
git submodule add https://github.com/haskell/aeson ./24/aeson
git submodule add https://github.com/coq-community/proviola.git ./06/proviola
git submodule add https://github.com/coq-community/coq-plugin-template.git ./06/coq-plugin-template
git submodule add https://github.com/coq-community/semantics.git ./06/semantics
git submodule add https://github.com/coq-community/autosubst.git ./06/autosubst
git submodule add https://github.com/coq-community/qarith-stern-brocot.git ./06/qarith-stern-brocot
git submodule add https://github.com/UCSD-PL/proverbot9001.git ./06/proverbot9001
git submodule add https://github.com/QuickChick/QuickChick.git ./06/QuickChick
git submodule add https://github.com/LPCIC/coq-elpi ./06/coq-elpi
git submodule add https://github.com/uds-psl/autosubst-metacoq.git ./06/autosubst-metacoq
git submodule add https://github.com/coq-community/reduction-effects.git ./06/reduction-effects
git submodule add https://github.com/coq-community/almost-full.git ./06/almost-full
git submodule add https://github.com/gclaramunt/CoqWorkshop.git ./06/CoqWorkshop
git submodule add https://github.com/actions/runner.git ./06/runner
git submodule add https://github.com/coq-community/buchberger.git ./06/buchberger
git submodule add https://github.com/sweirich/corespec.git ./06/corespec
git submodule add https://github.com/coq-community/math-classes.git ./06/math-classes
git submodule add https://github.com/querycert/qcert.git ./06/qcert
git submodule add https://github.com/coq-community/docker-coq.git ./06/docker-coq
git submodule add https://github.com/typelead/eta.git ./06/eta
git submodule add https://github.com/Xiving/coq-ctproxy.git ./06/coq-ctproxy
git submodule add https://github.com/coq-community/docker-coq-action.git ./06/docker-coq-action
git submodule add https://github.com/MetaCoq/metacoq.git ./06/metacoq
git submodule add https://github.com/coq-community/coq-mmaps.git ./06/coq-mmaps
git submodule add https://github.com/coq-community/coq-dpdgraph.git ./06/coq-dpdgraph
git submodule add https://github.com/coq-community/coqeal.git ./06/coqeal
git submodule add https://github.com/math-comp/math-comp ./06/math-comp
git submodule add https://github.com/coq-community/dblib.git ./06/dblib
git submodule add https://github.com/evryfs/github-actions-runner-operator.git ./06/github-actions-runner-operator
git submodule add https://github.com/math-comp/hierarchy-builder.git ./06/hierarchy-builder
git submodule add https://github.com/hasura/graphql-engine.git ./06/graphql-engine
git submodule add https://github.com/coq-community/hydra-battles.git ./06/hydra-battles
git submodule add https://github.com/coq-community/matrix_canonical_forms.git ./06/matrix_canonical_forms
git submodule add https://github.com/AbsInt/CompCert.git ./06/CompCert
git submodule add https://github.com/proofengineering/proofengineering-bib.git ./06/proofengineering-bib
git submodule add https://github.com/coq/coq.git ./06/introspector/root/default/.opam-switch/sources/coq.8.17.dev
git submodule add https://github.com/mattam82/Coq-Equations ./06/introspector/root/default/.opam-switch/sources/coq-equations.dev
git submodule add https://github.com/coq/coq.git ./06/introspector/root/default/.opam-switch/sources/coq-core.8.17.dev
git submodule add https://github.com/coq-community/templates.git ./06/introspector/root/default/.opam-switch/sources/coq-ext-lib.dev
git submodule add https://github.com/fblanqui/color.git ./06/introspector/root/default/.opam-switch/sources/coq-color.dev
git submodule add https://github.com/coq/coq.git ./06/introspector/root/default/.opam-switch/sources/coqide-server.8.17.dev
git submodule add https://github.com/Matafou/LibHyps ./06/introspector/root/default/.opam-switch/sources/coq-libhyps.dev
git submodule add https://github.com/Lysxia/coq-ceres ./06/introspector/root/default/.opam-switch/sources/coq-ceres.dev
git submodule add https://github.com/snu-sf/paco.git ./06/introspector/root/default/.opam-switch/sources/coq-paco.dev
git submodule add https://github.com/coq/coq.git ./06/introspector/root/default/.opam-switch/sources/coq-stdlib.8.17.dev
git submodule add https://github.com/coq-community/coq-community.github.io.git ./06/coq-community.github.io
git submodule add https://github.com/tchajed/coq-project-template.git ./06/coq-project-template
git submodule add https://github.com/coq/opam-coq-archive.git ./06/opam-coq-archive
git submodule add https://github.com/coq-community/sudoku.git ./06/sudoku
git submodule add https://github.com/coq-community/coqdocjs.git ./06/coqdocjs
git submodule add https://github.com/princeton-vl/CoqGym.git ./06/CoqGym
git submodule add https://github.com/yannl35133/metacoq-docs.git ./06/metacoq-docs
git submodule add https://github.com/coq-community/generic-environments.git ./06/generic-environments
git submodule add https://github.com/shayan-najd/NativeMetaprogramming.git ./06/NativeMetaprogramming
git submodule add https://github.com/coq-community/coqtail-math.git ./06/coqtail-math
git submodule add https://github.com/coq-community/jmlcoq.git ./06/jmlcoq
git submodule add https://github.com/HoTT/Coq-HoTT.git ./06/Coq-HoTT
git submodule add https://github.com/sdiehl/wiwinwlh.git ./06/wiwinwlh
git submodule add https://github.com/HOL-Theorem-Prover/HOL.git ./06/HOL
git submodule add https://github.com/luchihoratiu/debug-via-ssh.git ./06/debug-via-ssh
git submodule add https://github.com/vellvm/vellvm.git ./06/vellvm
git submodule add https://github.com/coq-community/run-coq-bug-minimizer.git ./06/run-coq-bug-minimizer
git submodule add https://github.com/coq-community/coqffi.git ./06/coqffi
git submodule add https://github.com/fblanqui/color.git ./06/color
git submodule add https://github.com/mit-plv/fiat-crypto.git ./06/fiat-crypto
git submodule add https://github.com/DeepSpec/sf.git ./06/sf
git submodule add https://github.com/CertiCoq/certicoq.git ./06/certicoq
git submodule add https://github.com/coq-community/bits.git ./06/bits
git submodule add https://github.com/MetaCoq/metacoq.github.io.git ./06/metacoq.github.io
git submodule add https://github.com/tcardonne/docker-github-runner.git ./06/docker-github-runner
git submodule add https://github.com/OffcierCia/DeFi-Developer-Road-Map.git ./06/DeFi-Developer-Road-Map
git submodule add https://github.com/uds-psl/metacoq_plugins.git ./06/metacoq_plugins
git submodule add https://github.com/coq-community/goedel.git ./06/goedel
git submodule add https://github.com/coq-community/coq-performance-tests.git ./06/coq-performance-tests
git submodule add https://github.com/Matafou/LibHyps.git ./06/LibHyps
git submodule add https://github.com/uds-psl/metacoq-nested-induction.git ./06/metacoq-nested-induction
git submodule add https://github.com/myoung34/docker-github-actions-runner.git ./06/docker-github-actions-runner
git submodule add https://github.com/kyoDralliam/genxs.git ./06/genxs
git submodule add https://github.com/HoTT/book.git ./06/book
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/build/coq-metacoq-quotation.dev
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/build/coq-metacoq-safechecker.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/build/coq-core.dev
git submodule add https://github.com/ejgallego/coq-serapi.git ./06/.opam/default/.opam-switch/build/coq-lsp.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/sources/coq-stdlib.8.18.dev
git submodule add https://github.com/AbsInt/CompCert.git ./06/.opam/default/.opam-switch/sources/coq-compcert.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/sources/coqide-server.dev
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/sources/coq-metacoq-quotation.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/sources/coqide-server.8.18.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/sources/coq-stdlib.dev
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/sources/coq-metacoq-safechecker-plugin.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/sources/coq-core.8.18.dev
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/sources/coq-metacoq-safechecker.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/sources/coq.dev
git submodule add https://github.com/coq/coq.git ./06/.opam/default/.opam-switch/sources/coq-core.dev
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/sources/coq-metacoq-erasure.dev
git submodule add https://github.com/DeepSpec/InteractionTrees ./06/.opam/default/.opam-switch/sources/coq-itree.dev
git submodule add https://github.com/ejgallego/coq-serapi.git ./06/.opam/default/.opam-switch/sources/coq-lsp
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/sources/coq-metacoq.dev
git submodule add https://github.com/snu-sf/paco.git ./06/.opam/default/.opam-switch/sources/coq-vst.dev
git submodule add https:///github.com/metacoq/metacoq.git ./06/.opam/default/.opam-switch/sources/coq-metacoq-erasure-plugin.dev
git submodule add https://github.com/snu-sf/paco.git ./06/.opam/default/.opam-switch/sources/coq-vst-zlist.dev
git submodule add https://github.com/vellvm/vellvm ./06/.opam/default/.opam-switch/sources/helix
git submodule add https://github.com/christ2go/gherkin.git ./06/gherkin
git submodule add https://github.com/smtcoq/sniper.git ./06/sniper
git submodule add https://github.com/coq-community/comp-dec-modal.git ./06/comp-dec-modal
git submodule add https://github.com/mattam82/Coq-Equations.git ./06/Coq-Equations
git submodule add https://github.com/coq-community/tarjan.git ./06/tarjan
git submodule add https://github.com/uds-psl/coq-library-undecidability.git ./06/coq-library-undecidability
git submodule add https://github.com/coq-community/reglang.git ./06/reglang
git submodule add https://github.com/coq-community/templates.git ./06/templates
git submodule add https://github.com/coq-community/aac-tactics.git ./06/aac-tactics
git submodule add https://github.com/Mtac2/Mtac2.git ./06/Mtac2
git submodule add https://github.com/PrincetonUniversity/VST.git ./06/VST
git submodule add https://github.com/thery/coqprime.git ./06/coqprime
git submodule add https://github.com/tchajed/ltac2-tutorial.git ./06/ltac2-tutorial
git submodule add https://github.com/DeepSpec/dsss18.git ./06/dsss18
git submodule add https://github.com/csgordon/rgref-agda.git ./06/rgref-agda
git submodule add https://github.com/csgordon/bedrock.git ./06/bedrock
git submodule add https://github.com/coq-community/graph-theory.git ./06/graph-theory
git submodule add https://github.com/coq-community/gaia.git ./06/gaia
git submodule add https://github.com/coq-community/bignums.git ./06/bignums
git submodule add https://github.com/coq-community/HighSchoolGeometry.git ./06/HighSchoolGeometry
git submodule add https://github.com/ocaml/ocaml.git ./06/ocaml
git submodule add https://github.com/coq-community/lemma-overloading.git ./06/lemma-overloading
git submodule add https://github.com/coq-community/coq-ext-lib.git ./06/coq-ext-lib
git submodule add https://github.com/csgordon/rgref.git ./06/rgref
git submodule add https://github.com/coq-community/chapar.git ./06/chapar
git submodule add https://github.com/CakeML/cakeml.git ./06/cakeml
git submodule add https://github.com/DeepSpec/dsss17.git ./06/dsss17
git submodule add https://github.com/DeepSpec/InteractionTrees.git ./06/InteractionTrees
git submodule add https://github.com/coq/ltac2.git ./06/ltac2
git submodule add https://github.com/actions/runner-images.git ./06/runner-images
git submodule add https://github.com/coq-community/manifesto.git ./06/manifesto
git submodule add https://github.com/coq-community/coq-100-theorems.git ./06/coq-100-theorems
git submodule add https://github.com/janestreet/core.git ./06/core
git submodule add https://github.com/NixOS/nixpkgs.git ./06/nixpkgs
git submodule add https://github.com/jonico/awesome-runners.git ./06/awesome-runners
git submodule add https://github.com/coq-community/bertrand.git ./06/bertrand
git submodule add https://github.com/coq-community/huffman.git ./06/huffman
git submodule add https://github.com/coq-community/corn.git ./06/corn
git submodule add https://github.com/coq-community/regexp-Brzozowski.git ./06/regexp-Brzozowski
git submodule add https://github.com/AU-COBRA/ConCert.git ./06/ConCert
git submodule add https://github.com/coq-community/coq-art.git ./06/coq-art
git submodule add https://github.com/coq-community/atbr.git ./06/atbr
git submodule add https://github.com/coq-community/coq-nix-toolbox.git ./06/coq-nix-toolbox
git submodule add https://github.com/coq-community/docker-base.git ./06/docker-base
git submodule add https://github.com/plclub/hs-to-coq.git ./06/hs-to-coq
git submodule add https://github.com/coq-community/vscoq.git ./06/vscoq
git submodule add https://github.com/haslab/ccomp-simd.git ./06/ccomp-simd
git submodule add https://github.com/coq/coq.git ./06/coq
git submodule add https://github.com/liesnikov/subterm-metacoq.git ./06/subterm-metacoq
git submodule add https://github.com/coq-community/fourcolor.git ./06/fourcolor
git submodule add https://github.com/sifive/Kami.git ./06/Kami
git submodule add https://github.com/coq-community/hoare-tut.git ./06/hoare-tut
git submodule add https://github.com/uds-psl/metacoq-examples-coqws.git ./06/metacoq-examples-coqws
git submodule add https://github.com/coq-community/coqoban.git ./06/coqoban
git submodule add https://github.com/philips-labs/terraform-aws-github-runner.git ./06/terraform-aws-github-runner
git submodule add https://github.com/actions/actions-runner-controller.git ./06/actions-runner-controller
git submodule add https://github.com/polyml/polyml.git ./06/polyml
git submodule add https://github.com/vellvm/vellvm ./06/helix
git submodule add https://github.com/coq-community/paramcoq.git ./06/paramcoq
git submodule add https://github.com/coq-community/pocklington.git ./06/pocklington
git submodule add https://github.com/JasonGross/metacoq-lob.git ./06/metacoq-lob
git submodule add https://github.com/coq-community/stalmarck.git ./06/stalmarck
git submodule add https://github.com/coq-community/alea.git ./06/alea
git submodule add https://github.com/magmide/magmide.git ./06/magmide
git submodule add https://github.com/ejgallego/coq-serapi ./06/coq-serapi
git submodule add https://github.com/FStarLang/FStar.git ./06/FStar
git submodule add https://github.com/machulav/ec2-github-runner.git ./06/ec2-github-runner
git submodule add https://github.com/coq-community/awesome-coq.git ./06/awesome-coq
git submodule add https://github.com/coq-community/apery.git ./06/apery
git submodule add https://github.com/coq-community/topology.git ./06/topology
git submodule add https://github.com/terraform-google-modules/terraform-google-github-actions-runners.git ./06/terraform-google-github-actions-runners
git submodule add https://github.com/clarus/coq-clojure-extraction ./12/coq-clojure-extraction
git submodule add https://github.com/edolstra/flake-compat ./12/flake-compat
git submodule add https://github.com/joaotavora/eglot ./12/eglot
git submodule add https://github.com/emacs-straight/external-completion ./12/external-completion
git submodule add https://github.com/Kaptch/coq-lsp-emacs ./12/coq-lsp-emacs
git submodule add https://github.com/arthuraa/emacs-files ./12/emacs-files
git submodule add https://github.com/ejgallego/coq-lsp ./12/coq-lsp
git submodule add https://github.com/kalai-transpiler/kalai ./12/kalai
git submodule add https://github.com/sol/aeson-qq ./19/aeson-qq
git submodule add https://github.com/martinrehfeld/wai-example ./19/wai-example
git submodule add https://github.com/databrary/databrary.git ./16/databrary
git submodule add https://github.com/biocad/servant-openapi3 ./16/servant-openapi3
git submodule add https://github.com/composewell/streamly ./16/flora-server/dist-newstyle/src/streamly-c21fac2f29826a42
git submodule add https://github.com/flora-pm/wai-middleware-heartbeat ./16/flora-server/dist-newstyle/src/wai-middl_-cd0da7a1137ee091
git submodule add https://github.com/supki/envparse ./16/flora-server/dist-newstyle/src/envparse-c6092a80e101d449
git submodule add https://github.com/kleidukos/pg-transact-effectful ./16/flora-server/dist-newstyle/src/pg-transa_-4da824ceaba5cd3e
git submodule add https://github.com/saurabhnanda/odd-jobs ./16/flora-server/dist-newstyle/src/odd-jobs-105beed21b31f436
git submodule add https://github.com/kleidukos/servant-effectful ./16/flora-server/dist-newstyle/src/servant-e_-f03c8d45d7065eb5
git submodule add https://github.com/fimad/prometheus-haskell ./16/flora-server/dist-newstyle/src/prometheu_-e862cbca3f3df6bf
git submodule add https://github.com/flora-pm/flora-server ./16/flora-server
git submodule add https://github.com/haskell-servant/servant ./16/servant
git submodule add https://github.com/haskell-servant/example-servant-persistent ./16/example-servant-persistent
git submodule add https://github.com/digitallyinduced/ihp ./16/ihp
git submodule add https://github.com/haskell-servant/servant-swagger-ui ./16/servant-swagger-ui
git submodule add https://github.com/uds-psl/metacoq-examples-coqws ./16/sources/papers/2006.15135/metacoq-examples-coqws
git submodule add https://github.com/nick8325/quickcheck ./16/quickcheck
git submodule add https://github.com/phadej/cabal-fmt ./16/cabal-fmt
git submodule add https://github.com/parsonsmatt/foundation ./16/wai/dist-newstyle/src/foundation-7095e3dda3594362
git submodule add https://github.com/parsonsmatt/hs-memory ./16/wai/dist-newstyle/src/hs-memory-7a9413d2a1172f3d
git submodule add https://github.com/yesodweb/wai ./16/wai
git submodule add https://github.com/biocad/openapi3 ./16/openapi3
git submodule add https://github.com/ch1bo/servant-exceptions ./16/servant-exceptions
git submodule add https://github.com/swagger-api/swagger-codegen ./16/swagger-codegen
git submodule add https://github.com/serokell/nixfmt ./16/nixfmt
git submodule add https://github.com/souffle-lang/souffle ./16/souffle
git submodule add https://github.com/xaviershay/haskell-servant-react-auth-example ./16/haskell-servant-react-auth-example
git submodule add https://github.com/GetShopTV/swagger2 ./16/swagger2
git submodule add https://github.com/MaartenFaddegon/Hoed ./17/Hoed
git submodule add https://github.com/python/peps.git ./17/introspector/datasources/python/pep/peps
git submodule add https://github.com/python/pyperformance.git ./17/introspector/input/pyperformance
git submodule add https://github.com/YoloSwagTeam/ast2json.git ./17/introspector/input/ast2json
git submodule add https://github.com/jelmer/dulwich.git ./17/experiments/dulwich
git submodule add https://github.com/LAION-AI/Open-Assistant.git ./17/experiments/Open-Assistant
git submodule add https://github.com/friguzzi/cplint.git ./17/experiments/cplint
git submodule add https://github.com/srossross/Meta.git ./17/experiments/Meta
git submodule add https://github.com/herumi/xbyak ./17/experiments/dgl
git submodule add https://github.com/huggingface/transformers.git ./17/experiments/transformers
git submodule add https://github.com/EleutherAI/gpt-neox.git ./17/experiments/gpt-neox
git submodule add https://github.com/facebookresearch/ParlAI.git ./17/experiments/ParlAI
git submodule add https://github.com/facebook/zstd.git ./17/experiments/pytorch
git submodule add https://github.com/RasaHQ/rasa.git ./17/experiments/bots/rasa
git submodule add https://github.com/autogluon/autogluon.git ./17/experiments/autogluon
git submodule add https://github.com/python/peps.git ./17/experiments/introspector/datasources/python/pep/peps
git submodule add https://github.com/python/pyperformance.git ./17/experiments/introspector/input/pyperformance
git submodule add https://github.com/YoloSwagTeam/ast2json.git ./17/experiments/introspector/input/ast2json
git submodule add https://github.com/pykeen/pykeen.git ./17/experiments/pykeen
git submodule add https://github.com/networkx/networkx.git ./17/experiments/networkx
git submodule add https://github.com/dflook/python-minifier.git ./17/experiments/python-minifier
git submodule add https://github.com/gitpython-developers/GitPython.git ./17/experiments/GitPython
git submodule add https://github.com/oneapi-src/oneDNN.git ./17/experiments/oneDNN
git submodule add https://github.com/rapidsai/cugraph.git ./17/experiments/cugraph
git submodule add https://github.com/KDAB/KDDockWidgets.git ./17/experiments/perf/hotspot/dep/KDDockWidgets
git submodule add https://github.com/KDAB/hotspot.git ./17/experiments/perf/hotspot
git submodule add https://github.com/foundry2D/hperf.git ./17/experiments/perf/hperf
git submodule add https://github.com/google/perf_data_converter.git ./17/experiments/perf/perf_data_converter
git submodule add https://github.com/microsoft/GODEL.git ./17/experiments/GODEL
git submodule add https://github.com/awslabs/dgl-ke.git ./17/experiments/dgl-ke
git submodule add https://github.com/cs230-stanford/cs230-code-examples.git ./17/experiments/cs230-code-examples
git submodule add https://github.com/mozilla/sccache.git ./17/experiments/sccache
git submodule add https://github.com/blazegraph/database.git ./17/experiments/blazegraph-database/database
git submodule add https://github.com/blazegraph/database.git ./17/experiments/blazegraph-database
git submodule add https://github.com/explosion/spaCy.git ./17/experiments/spaCy
git submodule add https://github.com/ikamensh/flynt.git ./17/experiments/flynt
git submodule add https://github.com/benf2004/ChatGPT-Prompt-Genius.git ./17/experiments/chatgpt/export/ChatGPT-Prompt-Genius
git submodule add https://github.com/torvalds/linux.git ./17/experiments/linux
git submodule add https://github.com/autoconf-archive/autoconf-archive.git ./17/experiments/auto/autoconf-archive
git submodule add https://github.com/vesoft-inc/nebula.git ./17/experiments/nebula
git submodule add https://github.com/requests/requests-threads.git ./17/experiments/requests-threads
git submodule add https://github.com/tensorflow/tensorflow.git ./17/experiments/tensorflow
git submodule add https://github.com/brendangregg/perf-tools.git ./17/experiments/perf-tools
git submodule add https://github.com/pionxzh/chatgpt-exporter.git ./17/experiments/chatgpt-exporter
git submodule add https://github.com/bazelbuild/bazelisk.git ./17/experiments/bazelisk
git submodule add https://github.com/fossasia/visdom.git ./17/experiments/visdom
git submodule add https://github.com/iovisor/bpftrace.git ./17/experiments/bpftrace
git submodule add https://github.com/libbpf/blazesym ./17/experiments/bpftrace/bcc
git submodule add https://github.com/libbpf/libbpf.git ./17/experiments/bpftrace/libbpf
git submodule add https://github.com/python/cpython.git ./17/experiments/cpython
git submodule add https://github.com/gcc-mirror/gcc.git ./17/experiments/gcc
git submodule add https://github.com/jfbastien/papers.git ./17/experiments/papers
git submodule add https://github.com/dandoh/web-haskell ./23/web-haskell
git submodule add https://github.com/brendanhay/amazonka ./23/amazonka
git submodule add https://github.com/morpheusgraphql/mythology-api ./23/mythology-api
git submodule add https://github.com/ku-fpg/data-reify ./26/data-reify
git submodule add https://github.com/rudymatela/express ./26/express
git submodule add https://github.com/haskell-beam/beam ./26/beam
git submodule add https://github.com/rudymatela/extrapolate ./26/extrapolate
git submodule add https://github.com/ucsd-progsys/liquidhaskell ./26/liquidhaskell
git submodule add https://github.com/meta-introspector/th-desugar ./26/th-desugar
git submodule add https://github.com/rudymatela/speculate ./26/speculate
git submodule add https://github.com/ucsd-progsys/liquidhaskell-tutorial.git ./26/liquidhaskell-tutorial
git submodule add https://github.com/serras/emacs-haskell-tutorial ./04/emacs-haskell-tutorial
git submodule add https://github.com/hbin/smart-shift ./04/smart-shift
git submodule add https://github.com/taktoa/wasm ./28/wasm
git submodule add https://github.com/sonic-lang/sonic-desugar ./28/sonic-desugar
git submodule add https://github.com/proglang/AlgST ./28/AlgST
git submodule add https://github.com/vi/websocat ./25/websocat
git submodule add https://github.com/vermiculus/graphql.el.git/ ./25/graphql.el
git submodule add https://github.com/parsonsmatt/foundation ./25/wai/dist-newstyle/src/foundation-7095e3dda3594362
git submodule add https://github.com/parsonsmatt/hs-memory ./25/wai/dist-newstyle/src/hs-memory-7a9413d2a1172f3d
git submodule add https://github.com/mniip/th-tc ./27/th-tc
git submodule add https://github.com/obsidiansystems/aeson-gadt-th ./27/aeson-gadt-th
git submodule add https://github.com/fpco/th-utilities ./27/th-utilities
git submodule add https://github.com/mgsloan/th-reify-many ./27/th-reify-many
git submodule add https://github.com/ku-fpg/hermit ./27/hermit
git submodule add https://github.com/yesodweb/yesod-scaffold ./27/yesod-scaffold
git submodule add https://github.com/vacationlabs/record-splicer ./27/record-splicer
git submodule add https://github.com/thephoeron/quipper-language ./27/quipper-language
git submodule add https://github.com/glguy/th-abstraction ./27/th-abstraction
git submodule add https://github.com/ku-fpg/kansas-lava ./27/kansas-lava
git submodule add https://github.com/ku-fpg/marked-pretty ./27/marked-pretty
git submodule add https://github.com/feuerbach/traverse-with-class.git ./22/traverse-with-class
git submodule add https://github.com/jmikedupont2/morpheus-graphql.git ./22/morpheus-graphql
git submodule add https://github.com/obsidiansystems/obelisk ./21/obelisk
git submodule add https://github.com/vadimbakaev/flatmap.io ./21/flatmap.io
git submodule add https://github.com/timjs/tophat-haskell ./21/tophat-haskell
