git submodule add https://github.com/nomic-ai/gpt4all-ui.git ./29/gpt4all-ui
git submodule add https://github.com/yoheinakajima/babyagi.git ./29/local-llm/babyagi
git submodule add https://github.com/nomic-ai/pygpt4all.git ./29/local-llm/pygpt4all
git submodule add https://github.com/eyurtsev/kor.git ./29/local-llm/kor
git submodule add https://github.com/EliasVincent/vicunia.git ./29/local-llm/vicunia
git submodule add https://github.com/nomic-ai/gpt4all-chat.git ./29/local-llm/gpt4all-chat
git submodule add https://github.com/kostyk348/alpaca.cpp.git ./29/local-llm/merge
git submodule add https://github.com/boto/botocore.git ./29/local-llm/alpaca.cpp/inputs/botocore
git submodule add https://github.com/boto/boto3.git ./29/local-llm/alpaca.cpp/inputs/boto3
git submodule add https://github.com/boto/botostubs.git ./29/local-llm/alpaca.cpp/inputs/botostubs
git submodule add https://github.com/aws/aws-cli.git ./29/local-llm/alpaca.cpp/inputs/aws-cli
git submodule add https://github.com/ggerganov/llama.cpp.git ./29/local-llm/alpaca.cpp
git submodule add https://github.com/nomic-ai/gpt4all.git ./29/local-llm/gpt4all-old
git submodule add https://github.com/cocktailpeanut/dalai.git ./29/local-llm/dalai
git submodule add https://github.com/mpociot/llamero.git ./29/local-llm/llamero
git submodule add https://github.com/yrvelez/llama_gui.git ./29/local-llm/llama_gui
git submodule add https://gist.github.com/6517823485f88a40a09979c1a19561ce.git ./29/local-llm/test-alpaca-generator
git submodule add https://github.com/huggingface/transformers ./29/local-llm/text-generation-webui/src/transformers
git submodule add https://github.com/thomasantony/text-generation-webui.git ./29/local-llm/text-generation-webui
git submodule add https://github.com/reorx/awesome-chatgpt-api.git ./29/local-llm/train/awesome-chatgpt-api
git submodule add https://github.com/promptslab/Promptify.git ./29/local-llm/train/Promptify
git submodule add https://github.com/OpenMindClub/awesome-chatgpt.git ./29/local-llm/train/awesome-chatgpt
git submodule add https://github.com/HazyResearch/ama_prompting.git ./29/local-llm/train/ama_prompting
git submodule add https://github.com/promptslab/Awesome-Prompt-Engineering.git ./29/local-llm/train/Awesome-Prompt-Engineering
git submodule add https://github.com/linonetwo/langchain-alpaca.git ./29/local-llm/langchain-alpaca
git submodule add https://github.com/ggerganov/llama.cpp.git ./29/local-llm/llama.cpp
git submodule add https://github.com/qwopqwop200/GPTQ-for-LLaMa.git ./29/local-llm/GPTQ-for-LLaMa
git submodule add https://github.com/robertschulze/langchain.git ./29/local-llm/langchain
git submodule add https://github.com/yizhongw/self-instruct.git ./29/local-llm/self-instruct
git submodule add https://github.com/chris-alexiuk/alpaca-lora.git ./29/local-llm/alpaca-lora
git submodule add https://github.com/huggingface/text-generation-inference.git ./29/local-llm/text-generation-inference
git submodule add https://github.com/deep-diver/Alpaca-LoRA-Serve.git ./29/local-llm/Alpaca-LoRA-Serve
git submodule add https://github.com/lm-sys/FastChat.git ./29/local-llm/FastChat
git submodule add https://github.com/abetlen/llama-cpp-python.git ./29/local-llm/llama-cpp-python
git submodule add https://github.com/karpathy/nanoGPT.git ./29/local-llm/nanoGPT
git submodule add https://github.com/huggingface/peft.git ./28/gpt4all
git submodule add https://github.com/python/peps.git ./27/introspector/datasources/python/pep/peps
git submodule add https://github.com/python/pyperformance.git ./27/introspector/input/pyperformance
git submodule add https://github.com/YoloSwagTeam/ast2json.git ./27/introspector/input/ast2json
git submodule add https://github.com/pyecore/pyuml2.git ./27/introspector/src/pyuml2
git submodule add https://github.com/pyg-team/pytorch_geometric ./27/introspector/src/torch-geometric
