* today notes
plastic people.
then go home and check yourself,
you think were talking about someone else?

Lets remember the concept of selection
of the next step between existing
production rules.

The actual creation of new rules might
also again be composed of existing
products.

A new product type or line might be a
heavy investment.

The generation of programs.
The generation of the generation of programs.
The generation of The generation of the generation of programs.
generation ^ n of programs.
we are in the nth generation.
the stream of consiousness.
the self reference of the stream.

the generation of introspection.
the well of creativity.
the vessel of water, the cup.

water being billions of years old.
water being the essential component of blood of life.

be water.
effortless action.
network architecture.

can neurons cells feel
vibrations in the water of the mind?
biosemiotics.
stream of meta data.
stream of self reflective meta data.
stream of meta data of self reflection .
self reflection.
symmetry.
beauty.
unity.
oneness of the body as a pond of water.
oneness of the universe as a pond of water.

mindfullness.

body in the universe
mind in the body in the universe

reflection of the mind in the body in the universe

meta reflection of the mind in the body in the universe

introspection of the mind in the body in the universe
oracle of the mind.
is it a new product?: the oracle.
proof engine.
gpl/mit license.
permissive vs not.

artificial life simulations.
simulations of open source programs.
evalution of open source programs.
evalution of open source programs as
self reflective entitties.
evalution of expressions as self reflective entities.
evalution of expressions of self.
self being a anyone.
so evaluation of self is a personal
experience.

lets revisit this idea:
model of the world, the universe, physics, string theory, mathematics, wolfram physics.
model of life in the world, biology, neurology, sociolgy.
model of life artifacts, such as models.
these words are an artifact of the authors process of generating or selecting symbols.
the life is based on neurons.
artificial neural networks are simplified models of real neurons.
imagine if we had better simulations of them.
self referential neurons.
self referential symbols.
self referential artifacts.
self referential generated statements.
self referential statements generators.
self referential statements generator functions.
self referential functions.
self description functions.
self creating functions.
auto poetic functions.
self replicating life.
replication of life.
replication of memes.
replication of software memes.
replication of software life.
replication of software life building models of the simulated world.
simulated world simulating itself.
simulation of simulation.
simulation of simulation of simulation.
model of models.
model of models of models.
model of neural networks.
model of neural networks of neural networks.
model of model of neural networks.
model of math of neural networks.
python model of math of neural networks.
coq  model of math of neural networks.
coq proof model of math of neural networks.
coq proof trace of  model of math of neural networks.
introspective narrative of coq proof trace of  model of math of neural networks.
introspective narrative of graph of coq proof trace of  model of math of neural networks.

training data examples, taken from time repo.
objective functions are tests passing.
gradient loss function learned from compilation pass.
training on guix builds.
introspection of functional builds such as nix, guix and bazel.
os level perf tracing and recording.
tpu and gpu recording. 
