git submodule add https://github.com/nsumner/antlr2pnf.git ./15/antlr2pnf
git submodule add https://github.com/GuntherRademacher/rr.git ./15/rr
git submodule add https://github.com/nsumner/antlr2cnf ./15/antlr2cnf
git submodule add https://github.com/antlr/antlr4 ./15/antlr4
git submodule add https://github.com/swabhs/joint-lstm-parser ./30/joint-lstm-parser
git submodule add https://github.com/meta-introspector/Transformer-DyNet.git ./30/Transformer-DyNet
git submodule add https://github.com/neulab/dynet-benchmark ./30/dynet-benchmark
git submodule add https://github.com/kamigaito/seq2seq-baseline-dynet ./30/seq2seq-baseline-dynet
git submodule add https://github.com/linexjlin/GPTs ./30/GPTs
git submodule add https://github.com/b30wulffz/automata-toolkit ./13/automata-toolkit
git submodule add https://github.com/200ok-ch/org-parser ./13/org-parser
git submodule add https://github.com/yugabyte/yugabyte-db.git ./13/yugabyte-db
git submodule add https://github.com/rflynn/regroup ./13/regroup
git submodule add https://github.com/meta-introspector/llama.cpp ./13/llama.cpp
git submodule add https://github.com/tlkh/NVStatsRecorder ./05/NVStatsRecorder
git submodule add https://github.com/tiangolo/sqlmodel ./11/sqlmodel
git submodule add https://github.com/saulpw/visidata.git ./11/visidata
git submodule add https://github.com/ray-project/ray ./11/ray
git submodule add https://github.com/agronholm/sqlacodegen ./11/sqlacodegen
git submodule add https://github.com/fair-acc/opencmw-cpp ./24/opencmw-cpp
git submodule add https://github.com/NVIDIA/gpu-operator ./03/gpu-operator
git submodule add https://github.com/NVIDIA/cccl ./03/cccl
git submodule add https://github.com/lanl/PPT.git ./03/TensorRT/PPT
git submodule add https://github.com/protocolbuffers/protobuf.git ./03/TensorRT
git submodule add https://github.com/dashazhangdake/NVBitFI-by-Time.git ./03/NVBitFI-by-Time
git submodule add https://github.com/NVIDIA/gpu-monitoring-tools ./03/gpu-monitoring-tools
git submodule add https://github.com/mirror/tclap ./03/DCGM/build/tclap
git submodule add https://github.com/open-source-parsers/jsoncpp ./03/DCGM/vendor/jsoncpp
git submodule add https://github.com/libevent/libevent ./03/DCGM/vendor/libevent
git submodule add https://github.com/catchorg/Catch2 ./03/DCGM/vendor/Catch2
git submodule add https://github.com/jbeder/yaml-cpp ./03/DCGM/vendor/yaml-cpp
git submodule add https://github.com/meta-introspector/fmt ./03/DCGM/vendor/fmt
git submodule add https://github.com/SergiusTheBest/plog ./03/DCGM/vendor/plog
git submodule add https://github.com/jbeder/yaml-cpp ./03/DCGM
git submodule add https://github.com/NVIDIA/dcgm-exporter ./03/dcgm-exporter
git submodule add https://github.com/romnn/nvbit-rs.git ./03/nvbit-rs
git submodule add https://github.com/therontarigo/nvcachetools ./03/nvcachetools
git submodule add https://github.com/yinengy/CUDA-Data-Race-Detector.git ./03/CUDA-Data-Race-Detector
git submodule add https://github.com/cloudcores/CuAssembler ./03/CuAssembler
git submodule add https://github.com/NVlabs/NVBit ./03/NVBit
git submodule add https://github.com/numba/numba ./03/numba
git submodule add https://github.com/accel-sim/accel-sim-framework ./03/accel-sim-framework
git submodule add https://github.com/mit-han-lab/streaming-llm ./03/streaming-llm
git submodule add https://github.com/divadnauj-GB/nvbitPERfi.git ./03/nvbitPERfi
git submodule add https://github.com/LLNL/BinFPE ./03/BinFPE
git submodule add https://github.com/meta-introspector/ggml-introspector ./08/ggml-introspector
git submodule add https://github.com/mistralai/mistral-src ./08/mistral-src
git submodule add https://github.com/su77ungr/CASALIOY ./29/CASALIOY
git submodule add https://github.com/h2oai/h2ogpt ./29/h2ogpt
git submodule add https://github.com/sigsep/open-unmix-pytorch ./29/umx.cpp
git submodule add https://github.com/farzingkh/EigenFlow ./29/EigenFlow
git submodule add https://github.com/AlliedToasters/dfencoder ./29/dfencoder
git submodule add https://github.com/meta-introspector/dynet ./29/dynet
git submodule add https://github.com/facebookresearch/faiss/ ./09/faiss
git submodule add https://github.com/ggerganov/llama.cpp ./09/llama.cpp2
git submodule add https://github.com/NVIDIA/cutlass ./09/cutlass
git submodule add https://github.com/nomic-ai/llama.cpp.git ./09/llama.cpp
git submodule add https://github.com/AMReX-Codes/amrex ./09/amrex
git submodule add https://github.com/geohot/cuda_ioctl_sniffer ./07/cuda_ioctl_sniffer
git submodule add https://github.com/cloudcores/CuAssembler ./07/CuAssembler
git submodule add https://github.com/adwaitjog/mafia ./07/mafia
git submodule add https://github.com/pola-rs/polars-cli ./07/polars-cli
git submodule add https://github.com/NVIDIA-Merlin/Merlin ./07/Merlin
git submodule add https://github.com/sanjosh/csdocs ./07/csdocs
git submodule add https://github.com/CMU-SAFARI/GPGPUSim-Ramulator ./07/GPGPUSim-Ramulator
git submodule add https://github.com/geoffxy/habitat ./07/habitat
git submodule add https://github.com/PAA-NCIC/DeepPerf ./07/DeepPerf
git submodule add https://github.com/apache/arrow ./07/arrow
git submodule add https://github.com/openai/openai-gemm ./07/openai-gemm
git submodule add https://github.com/NVIDIA/open-gpu-kernel-modules.git ./07/open-gpu-kernel-modules
git submodule add https://github.com/magit/magit.git ./19/magit
git submodule add https://github.com/mistralai/mistral-src ./19/mistral-src
git submodule add https://github.com/dabeaz/ply ./16/ply
git submodule add https://github.com/veselink1/refl-ht ./23/refl-ht
git submodule add https://github.com/stiger104/AutoEncoder ./26/AutoEncoder
git submodule add https://github.com/200ok-ch/org-parser ./14/org-parser
git submodule add https://github.com/yegor256/antlr2ebnf-maven-plugin ./14/antlr2ebnf-maven-plugin
git submodule add https://github.com/yegor256/naive-ebnf ./14/naive-ebnf
git submodule add https://github.com/pemistahl/grex ./14/grex
git submodule add https://github.com/antlr/grammars-v4 ./14/grammars-v4
git submodule add https://github.com/quarkusio/quarkus.git ./14/quarkus
git submodule add https://github.com/scriptsboy/Mirai.git ./14/Mirai
git submodule add https://github.com/meta-introspector/grammar-converter ./14/grammar-converter
git submodule add https://github.com/libevent/libevent ./04/libevent
git submodule add https://github.com/vearch/vearch.git ./04/vearch
git submodule add https://github.com/pkestene/cuda-proj-tmpl ./04/cuda-proj-tmpl
git submodule add https://github.com/Kitware/CMake ./04/CMake
git submodule add https://github.com/CannyLab/tsne-cuda ./04/tsne-cuda
git submodule add https://github.com/OpenNMT/CTranslate2 ./04/CTranslate2
git submodule add https://github.com/rpavlik/cmake-modules ./04/cmake-modules
git submodule add https://github.com/meta-introspector/deploy-pages.git ./01/deploy-pages
git submodule add https://github.com/actions/configure-pages ./01/configure-pages
git submodule add https://github.com/meta-introspector/upload-pages-artifact ./01/upload-pages-artifact
git submodule add https://github.com/NVIDIA/cuda-gdb ./10/cuda-gdb
git submodule add https://github.com/CarlQLange/chatgpt-arcana.el ./02/chatgpt-arcana.el
git submodule add https://github.com/johnstonskj/rdftools ./02/rdftools
git submodule add https://github.com/ahyatt/llm ./02/llm
git submodule add https://github.com/s-kostyaev/ellama ./02/ellama
git submodule add https://github.com/Tonic-AI/PolyGPT-alpha ./02/PolyGPT-alpha
git submodule add https://github.com/ericprud/shexc-mode-for-emacs ./02/shexc-mode-for-emacs
git submodule add https://github.com/VladimirAlexiev/shaclc-mode ./02/shaclc-mode
git submodule add https://github.com/RDFLib/pySHACL ./02/pySHACL
git submodule add https://github.com/mrtrizer/mojito-reflection ./22/mojito-reflection
git submodule add https://github.com/jsoysouvanh/Kodgen ./22/Kodgen
git submodule add https://github.com/google/googletest ./22/googletest
git submodule add https://github.com/matus-chochlik/mirror ./22/mirror
git submodule add https://github.com/google/googletest.git ./22/meta/deps/googletest/src
git submodule add https://github.com/skypjack/meta ./22/meta
git submodule add https://github.com/jgarvin/Cogflect ./22/Cogflect
git submodule add https://github.com/jsoysouvanh/Refureku ./22/Refureku
git submodule add https://github.com/chakaz/reflang ./22/reflang
git submodule add https://github.com/g-truc/glm ./22/archimedes
git submodule add https://github.com/skypjack/entt ./22/entt
git submodule add https://github.com/RAttab/reflect ./22/reflect
git submodule add https://github.com/wqking/metapp ./22/metapp
git submodule add https://github.com/veselink1/refl-cpp ./22/refl-cpp
git submodule add https://github.com/rttrorg/rttr ./22/rttr
git submodule add https://github.com/Neargye/magic_enum.git ./21/magic_enum
