git submodule add https://github.com/meta-introspector/menhir ./15/menhir
git submodule add https://github.com/exercism/coq ./15/exercism-coq
git submodule add https://github.com/meta-introspector/gbnf-nice-parser ./15/nice-parser
git submodule add https://github.com/jmikedupont2/unlimited-context-prompt-system.git ./13/unlimited-context-prompt-system
git submodule add https://github.com/ggerganov/ggml ./13/ggml
git submodule add https://github.com/jwiegley/emacs-async ./05/emacs-async
git submodule add https://github.com/meta-introspector/emacs-async-job-queue ./05/emacs-async-job-queue
git submodule add https://github.com/kurnevsky/llama-cpp.el ./05/llama-cpp.el
git submodule add https://github.com/Ptival/PeaCoq ./11/PeaCoq
git submodule add https://github.com/princeton-vl/CoqGym ./11/CoqGym
git submodule add https://github.com/meta-introspector/alec-is-not-coq-lsp ./11/alec-is-not-coq-lsp/temp/alec-is-not-coq-lsp
git submodule add https://github.com/ejgallego/coq-serapi.git ./11/alec-is-not-coq-lsp
git submodule add https://github.com/brando90/coq-serapi-python ./11/coq-serapi-python
git submodule add https://github.com/proofengineering/serapi-tests ./11/serapi-tests
git submodule add https://github.com/isabelle-prover/proving-contest-backends ./11/proving-contest-backends
git submodule add https://github.com/TNG/boost-python-examples ./06/boost-python-examples
git submodule add https://github.com/v8/v8 ./08/v8
git submodule add https://github.com/metacall/deploy ./08/deploy
git submodule add https://github.com/metacall/install ./08/install
git submodule add https://github.com/meta-introspector/Cppcamlexample.git ./09/Cppcamlexample
git submodule add https://github.com/fccm/embed-ocaml-c-mingw ./09/embed-ocaml-c-mingw
git submodule add https://github.com/ocaml-cmake/ocaml-cmake ./09/ocaml-cmake
git submodule add https://github.com/eatonphil/mod_ocaml ./09/mod_ocaml
git submodule add https://github.com/gmcabrita/embed-ocaml-c ./09/embed-ocaml-c
git submodule add https://github.com/nodejs/node ./07/node
git submodule add https://github.com/bombela/backward-cpp ./07/meta-call-core/build/_deps/backwardcpp-src
git submodule add https://github.com/gdabah/distorm.git ./07/meta-call-core/build/source/detours/funchook_detour/funchook/src/funchook
git submodule add https://github.com/metacall/core.git ./07/meta-call-core
git submodule add https://github.com/cmake-js/cmake-js ./07/cmake-js
git submodule add https://github.com/jxcore/jxcore ./07/jxcore
git submodule add https://github.com/nodesource/distributions ./07/nodesource-distributions
git submodule add https://github.com/mmomtchev/libnode ./07/libnode
git submodule add https://github.com/metacall/examples.git ./07/meta-call-examples
git submodule add https://github.com/metacall/embedding-nodejs-example ./07/meta-call-embedding-nodejs
git submodule add https://github.com/gares/vscoq-language-server ./12/vscoq-language-server
git submodule add https://github.com/meta-introspector/CompCert ./12/CompCert
git submodule add https://github.com/snu-sf/paco.git ./12/VST
git submodule add https://github.com/coq-community/vscoq/ ./12/vscoq
git submodule add https://github.com/coq-community/alea ./12/alea
git submodule add https://github.com/EasyCrypt/certicrypt ./12/certicrypt
git submodule add https://github.com/meta-introspector/gbnf-nice-parser ./17/gbnf_parser
git submodule add https://github.com/pierregobin/multiproj.git ./17/multiproj
git submodule add https://github.com/meta-introspector/gbnf-nice-parser ./17/gbnf-nice-parser-compare
git submodule add https://github.com/e-p-armstrong/augmental-universal/ ./23/augmental-universal
git submodule add https://github.com/bollu/deep-prosody ./23/deep-prosody
git submodule add https://github.com/ycros/koboldcpp/ ./23/koboldcpp
git submodule add https://github.com/6monthslater/6monthslater/ ./23/6monthslater
git submodule add https://github.com/nagolinc/AIStoryteller ./23/AIStoryteller
git submodule add https://github.com/dynaboard/ai-studio/ ./23/ai-studio
git submodule add https://github.com/erlebach/langchain_gordon_experiments/ ./23/langchain_gordon_experiments
git submodule add https://github.com/epfl-dlab/transformers-GCD-PR ./23/transformers-GCD-PR
git submodule add https://github.com/AlienKevin/llama.cpp ./23/AlienKevin-llama.cpp
git submodule add https://github.com/coq-community/coq-plugin-template ./14/coq-plugin-template
git submodule add https://github.com/QuickChick/QuickChick ./14/QuickChick
git submodule add https://github.com/LPCIC/coq-elpi.git ./14/coq-elpi
git submodule add https://github.com/IBM/openai-gym-ocaml ./14/openai-gym-ocaml
git submodule add https://github.com/ocaml/dune ./14/dune
git submodule add https://github.com/tsantosh7/COVID-19-Named-Entity-Recognition ./14/COVID-19-Named-Entity-Recognition
git submodule add https://github.com/karpathy/llama2.c ./14/llama2.c
git submodule add https://github.com/meta-introspector/openai-ocaml ./14/openai-ocaml
git submodule add https://github.com/LPCIC/elpi ./14/elpi
git submodule add https://github.com/flashlight/flashlight ./04/flashlight
git submodule add https://github.com/arrayfire/assets.git ./04/arrayfire/build/docs/html
git submodule add https://github.com/ThrowTheSwitch/Unity ./04/arrayfire/build/extern/ocl_cl2hpp-src
git submodule add https://github.com/arrayfire/glad.git ./04/arrayfire/build/extern/af_glad-src
git submodule add https://github.com/arrayfire/threads.git ./04/arrayfire/build/extern/af_threads-src
git submodule add https://github.com/cnugteren/CLBlast.git ./04/arrayfire/build/extern/ocl_clblast-src
git submodule add https://github.com/martinmoene/span-lite ./04/arrayfire/build/extern/span-lite-src
git submodule add https://github.com/arrayfire/clFFT.git ./04/arrayfire/build/extern/ocl_clfft-src
git submodule add https://github.com/gabime/spdlog.git ./04/arrayfire/build/extern/spdlog-src
git submodule add https://github.com/arrayfire/arrayfire-data.git ./04/arrayfire/build/extern/af_test_data-src
git submodule add https://github.com/arrayfire/assets.git ./04/arrayfire/build/extern/af_assets-src
git submodule add https://github.com/arrayfire/forge.git ./04/arrayfire/build/extern/af_forge-src
git submodule add https://github.com/arrayfire/arrayfire ./04/arrayfire
git submodule add https://github.com/emacs-ng/emacs-ng ./04/emacs-ng
git submodule add https://github.com/small-yellow-duck/keras_generator_tutorial ./04/keras_generator_tutorial
git submodule add https://github.com/thushv89/attention_keras ./04/attention_keras
git submodule add https://github.com/Microsoft/vcpkg.git ./04/vcpkg
git submodule add https://github.com/links-lang/links ./18/links
git submodule add https://github.com/reasonml/reason ./18/reason
git submodule add https://github.com/cs3110/textbook ./18/textbook
git submodule add https://github.com/yurug/menhir-error-recovery ./18/menhir-error-recovery
git submodule add https://github.com/let-def/lrgrep ./18/lrgrep
git submodule add https://github.com/BNFC/bnfc ./18/bnfc
git submodule add https://github.com/dmbaturin/bnfgen ./18/bnfgen
git submodule add https://github.com/jordwalke/rehp.git ./18/rehp
git submodule add https://github.com/mmcco/verified-parser-example ./18/verified-parser-example
git submodule add https://github.com/weavery/clarity.ml ./18/clarity.ml
git submodule add https://github.com/jhjourdan/C11parser ./18/C11parser
git submodule add https://github.com/nomic-ai/llama.cpp.git ./18/nomic-ai-llama.cpp.git
git submodule add https://github.com/Lelio-Brun/Obelisk ./18/Obelisk
git submodule add https://github.com/areverii/Alpaca ./18/Alpaca
git submodule add https://github.com/odashi/nmtkit ./01/dynet_examples/nmtkit
git submodule add https://github.com/neubig/lamtram ./01/dynet_examples/lamtram
git submodule add https://github.com/clab/lstm-parser ./01/dynet_examples/lstm-parser
git submodule add https://github.com/swabhs/joint-lstm-parser ./01/dynet_examples/joint-lstm-parser
git submodule add https://github.com/miguelballesteros/LSTM-punctuation ./01/dynet_examples/LSTM-punctuation
git submodule add https://github.com/danielhers/tupa ./01/dynet_examples/tupa
git submodule add https://github.com/elikip/bist-parser ./01/dynet_examples/bist-parser
git submodule add https://github.com/clab/rnng ./01/dynet_examples/rnng
git submodule add https://github.com/roeeaharoni/morphological-reinflection ./01/dynet_examples/morphological-reinflection
git submodule add https://github.com/elikip/htparser ./01/dynet_examples/htparser
git submodule add https://github.com/mfaruqui/morph-trans ./01/dynet_examples/morph-trans
git submodule add https://github.com/trevorcohn/mantis ./01/dynet_examples/mantis
git submodule add https://github.com/neubig/modlm ./01/dynet_examples/modlm
git submodule add https://github.com/clab/stack-lstm-ner ./01/dynet_examples/stack-lstm-ner
git submodule add https://github.com/neulab/xnmt/ ./01/dynet_examples/xnmt
git submodule add https://github.com/CoNLL-UD-2017/C2L2 ./01/dynet_examples/C2L2
git submodule add https://github.com/jbuckman/boilerplate-dynet-rnn-lm/ ./01/boilerplate-dynet-rnn-lm
git submodule add https://github.com/slanglab/dynet-framework ./01/dynet-framework
git submodule add https://github.com/meta-introspector/keras ./01/keras
git submodule add https://github.com/dbuenzli/rresult ./10/rresult
git submodule add https://github.com/ocaml/ocaml ./10/ocaml
git submodule add https://github.com/camlp5/camlp5 ./10/camlp5
git submodule add https://github.com/facebook/zstd ./10/zstd
git submodule add https://github.com/nlohmann/json ./02/json
git submodule add https://github.com/onnx/tensorflow-onnx ./02/tensorflow-onnx
git submodule add https://github.com/pplonski/keras2cpp ./02/keras2cpp
git submodule add https://github.com/Dobiasd/frugally-deep ./02/frugally-deep
git submodule add https://github.com/intel/ipp-crypto.git ./02/onnxruntime/build/Release/_deps/ipp_crypto-src
git submodule add https://github.com/apache/tvm-vta.git ./02/onnxruntime/build/Release/_deps/tvm-src
git submodule add https://github.com/onnx/onnx.git ./02/onnxruntime
git submodule add https://github.com/Dobiasd/FunctionalPlus ./02/FunctionalPlus
git submodule add https://github.com/meta-introspector/setup-ocaml ./21/setup-ocaml
