* forms replicating
from env to neurons in learning,
from neurons to env in writing,
feedback loop of neurons to each other.
structures represented in symbols.
structures replicate.
graphs replicate.
forms replicate.
forms evaluate to replicate and evaluate and operate
like the flowers evolve due to bee selection.

causing network to replicate and then
sampling the signal of the replication channel,
the genes or instructions of the meme is sampling the bytecode basically,
the goedel number.

every bit of code generated can have comments that trace the functions that created it
every function can name itself, describe itself in ast, quote itself, bootstrap itself recursivly.
the graph will be too large to process in one step
it will need continuous processing and intermediate steps.
the structure of the graph is important.
higher order structures can represent themselves in different ways.
structures that describe structures are special,
they are universes at higher levels of homotopy not sets of simple objects in HTT.

a platonic dialog represents a transfer or conflict or multiplication of vectors
or the path of processing itself.

** parameterized types in ppx-introspetor.
consider parameterized types in hott, coq.

consider type UU, and then
(UU1 UU2 total2) pair. so that we have two types in a pair.
the we can model parameterized types as chains of total2.
we might need other ways to construct arrays with other notation.

