git submodule add https://github.com/epsilla-cloud/epsilla-vectorstore.git ./30/epsilla-vectorstore
git submodule add https://github.com/epsilla-cloud/epsilla-python-client.git ./30/epsilla-python-client
git submodule add https://github.com/meta-introspector/ollama ./30/ollama
git submodule add https://github.com/jdagdelen/hyperDB ./30/hyperDB
git submodule add https://github.com/ggerganov/llama.cpp.git ./30/ollama-build
git submodule add https://github.com/pgvector/pgvector ./30/pgvector
git submodule add https://github.com/run-llama/llama_index ./30/llama_index
git submodule add https://github.com/epsilla-cloud/vectordb.git ./30/vectordb
git submodule add https://github.com/callahantiff/PheKnowLator ./30/PheKnowLator
git submodule add https://github.com/qdrant/qdrant ./30/qdrant
git submodule add https://github.com/oatpp/oatpp ./30/oatpp
git submodule add https://github.com/altescy/pdpcli.git ./13/pdpcli
git submodule add https://github.com/smaxaddington/AutoGPT ./13/AutoGPT
git submodule add https://github.com/pdpipe/pdpipe ./13/pdpipe
git submodule add https://github.com/kellyjonbrazil/jc ./13/jc
git submodule add https://github.com/meta-introspector/agent-action ./05/agent-action
git submodule add https://github.com/meta-introspector/k3s ./11/k3s
git submodule add https://github.com/AbsaOSS/k3d-action ./11/k3d-action
git submodule add https://github.com/docker/buildx ./11/buildx
git submodule add https://github.com/kaushalmodi/tomelr ./24/tomelr
git submodule add https://github.com/cask/cask.git ./24/emacs-data/vendor/emacs/packaging/cask
git submodule add https://github.com/MaskRay/ccls ./24/emacs-data/vendor/emacs/lsp/ccls
git submodule add https://github.com/meta-introspector/Elsa ./24/emacs-data/vendor/emacs/Elsa
git submodule add https://github.com/jmikedupont2/elpy ./24/emacs-data/vendor/emacs/elpy
git submodule add https://github.com/apache/arrow.git ./24/emacs-data/vendor/apache/arrow
git submodule add https://github.com/zweifisch/ollama ./24/emacs-data
git submodule add https://github.com/jmikedupont2/call-auto-gpt ./06/call-auto-gpt
git submodule add https://github.com/actions/checkout ./08/checkout
git submodule add https://github.com/spotify/luigi ./29/luigi
git submodule add https://github.com/ARM-software/armnn ./29/ctuning
git submodule add https://github.com/meta-introspector/langsmith-sdk ./12/langsmith-sdk
git submodule add https://github.com/meta-introspector/langchain ./12/langchain
git submodule add https://github.com/meta-introspector/langsmith-sdk ./12/genai-stack
git submodule add https://github.com/docker/compose ./19/compose
git submodule add https://github.com/mhagger/git-imerge ./17/git-imerge
git submodule add https://github.com/emacs-compat/compat ./23/compat
git submodule add https://github.com/jmikedupont2/emacs ./23/emacs
git submodule add https://github.com/tinygrad/tinygrad ./23/tinygrad
git submodule add https://github.com/tvraman/emacspeak ./23/emacspeak
git submodule add https://github.com/jmikedupont2/Morpheus-Hardhat ./26/Morpheus-Hardhat
git submodule add https://github.com/pnpm/pnpm ./26/pnpm
git submodule add https://github.com/ShishirPatil/gorilla ./14/gorilla
git submodule add https://github.com/KentoNishi/awesome-all-you-need-papers ./31/awesome-all-you-need-papers
git submodule add https://github.com/robertgoss/K---Theory.git ./31/K---Theory
git submodule add https://github.com/Cybercube21/Rasa-discord-bot.git ./31/Rasa-discord-bot
git submodule add https://github.com/FlorianAdler/AlgebraBonn.git ./31/AlgebraBonn
git submodule add https://github.com/paulpierre/RasaGPT ./31/RasaGPT
git submodule add https://github.com/DanGrayson/Ktheory.git ./31/Ktheory
git submodule add https://github.com/SethEBaldwin/K-theory.git ./31/K-theory-sage
git submodule add https://github.com/this-vijay/ktheory.git ./31/ktheory
git submodule add https://github.com/monologg/nlp-arxiv-daily.git ./31/nlp-arxiv-daily
git submodule add https://github.com/jmikedupont2/KtoIsabelle ./31/KtoIsabelle
git submodule add https://github.com/sagemath/sage.git ./31/sage
git submodule add https://github.com/yufei118liu/ML-project-new-start.git ./31/ML-project-new-start
git submodule add https://github.com/superiorlu/AiTreasureBox.git ./31/AiTreasureBox
git submodule add https://github.com/adebray/equivariant_homotopy_theory.git ./31/equivariant_homotopy_theory
git submodule add https://github.com/SimplicialCat/Simplicial_Group.git ./31/Simplicial_Group
git submodule add https://github.com/ecpeterson/FormalGeomNotes.git ./31/FormalGeomNotes
git submodule add https://github.com/halois/Berrick_K-Theory.git ./31/Berrick_K-Theory
git submodule add https://github.com/ldXiao/Master_Thesis_ldXiao.git ./31/Master_Thesis_ldXiao
git submodule add https://github.com/MuriloucoLouco/K-theory.git ./31/K-theory
git submodule add https://github.com/sm00th/bitlbee-discord ./20/bitlbee-discord
git submodule add https://github.com/jmikedupont2/foundry ./25/foundry
git submodule add https://github.com/crytic/slither ./25/slither
git submodule add https://github.com/newren/git-filter-repo ./25/git-filter-repo
git submodule add https://github.com/Morpheusais/Morpheus/ ./25/Morpheus
git submodule add https://github.com/meta-introspector/dask-gateway ./10/dask-gateway
git submodule add https://github.com/jupyterhub/action-k3s-helm ./10/action-k3s-helm
git submodule add https://github.com/peter-evans/create-pull-request ./10/create-pull-request
git submodule add https://github.com/cirruslabs/cirrus-cli ./10/cirrus-cli
git submodule add https://github.com/team-tonic-arena-hacks/autogen ./02/autogen
git submodule add https://github.com/max-pfeiffer/uvicorn-poetry ./02/uvicorn-poetry
git submodule add https://github.com/max-pfeiffer/python-poetry/ ./02/python-poetry
git submodule add https://github.com/docker/docker-py ./02/docker-py
git submodule add https://github.com/tree-sitter/tree-sitter ./27/tree-sitter
git submodule add https://github.com/joshcho/ChatGPT.el ./22/ChatGPT.el
git submodule add https://github.com/rksm/org-ai ./22/org-ai
git submodule add https://github.com/emacs-openai/chatgpt ./22/chatgpt
git submodule add https://github.com/karthink/gptel ./22/gptel
