* idea of the day

From the chaos emerges the form.
it emerge from the depth of the water.
the deep neural networks are like deep waters.
the networks are from the nature.
they represent the capacity.
the formations are formed by nature.
reminders and reminders of distant times, remnants.

The size and shape of the network given by parameters the genes.
The contents of the network given by experience.
internal and external experiences.
internal to the body, internal to the mind, internal to the internal of the mind.
external to the internal of the mind are the inputs.

we can think of the mind going out to the world to do the heros jouney
and come back with the elixir, the function.

so the function is the heros journey and represents the capacity of
the mind to function at higher levels.

it shows that the right time and place, timing and location is everything
for the effectivness.

like a musician, not only do you need to learn your part but also adapt
to the situtation.


Reinterpreting that,
You need to remember your mission and not forget what you are
doing when distractions arises.
This is the chaos that pulls you back into it,
or the real world that is more complex than your model.

* Building the build system.

The system builds from a point.
expanding the point to larger and larger size,
including more size. each size added represents a type of data.
each accumulation can be seen as an induction.
the pair of initialize and increase.
zero and sequence. base case and induction.
we can see it as functional interface.
going from simple to complex.
layers of complexity.
many different paths can be taken.

we consider the seed, the spore, the egg.

it contains the nutrients, food, needed inputs, partially application of
the function or requirements for life,
we can think of validating the required types as preconditions for life.

in the case of a message, a meme,
the life occurs in the mind of the beholder, the interpreter of the message,
the sustaining substrate of the mind,
the fertile ground that has the right conditions for life, for the meme
to live in the mind, to be invoked, to be copied.
the firing of neurons, the matching of patterns.
on multiple levels there are functions. dimensions of functions.
layers of functions of life.
limits and sizes.

* more ideas

make it easy to deploy and run code via git and roll back if fail.
