artificial superintelligence
ai agents
hyperon netamoto
filecoin
frameworks
methods
agi term
research papers
probablistic logical networks
neurosymbolic ai

* giza
decentralized infrastucture
defi
zkml models
decisions
risk
market conditions
trades
yields

trust assumptions
verifiability
ai agents
proof of reputation
attestations

mpc multi party computation
deploy ml models and zkapps
apps like rendering, ml
scalable, because you dont need to replicate computation with zkml
hide some of the data.
scaling.
submodules.
privacy.
verification.

Fran Algaba, 13:42

Sebastian Rod
trust triangle
agent may say things about itself, yourself,
someone else says something about you,
digital trust, organization, other users.
Identifiable agent.
ai ml applications will need attestations, on chain , zkp, reputation base on agents
agents need to identify themselves. stable agent. give agent identifier.
only for that agent.

maintain a proof or trust over time.
show me your id. verify id.
chain of assumptions or trust.
did the model change, training data.

context:
landscape of decentralized ai.
what is zkml.

alex balgirev.
hosting the model on the nodes.
