* ideas of the day.

Ideas are contractable back down to the mind where they disappear and reemerge from it.

We can think of the mind as the base case where the idea emerges from,
and then the idea is continuously deformed into shapes as it gets bigger and bigger outside or inside the mind but starting from a point.

Even stimulus from outside that might cause this, so we could think of a musical idea that we percieve
and then it deforms in the mind into different forms.

Now we can consider if two starting points are equivalent, if the idea emerges from the mind we can say they
are two ideas from the same mind at different times or originating from the space mind. 
from the outside we can just say this is an idea from this person, or they might change over time.
but the point is if we can reduce the idea to a point it can then dissappear into the mind and reemerge as a new point that we might
consider to be equivalent if it of the same type. 
E. Kant considered apriori ideas to be identical if they have the same abstract content. 

we dont know what is happening in there.

to reconsider or contemplate is to go back into the depths of the mind.

from the outside we can think of this as a point. also from inside it is also can be considered as point.
so in any case it will go normal senses in and via motor actions out being a neural interface of electric signals.


If we consider the idea of the principle of induction for contractibility in homotopy type theory, we could consider the mind as the zero element from which
we can contract or drag the ideas out of. 

We can map the semantics of the user interface to coq proof terms so that dragging a total2 gui element that represents a connection on the GUI creates
a total connection between the two objects denoted.
