git submodule add https://github.com/meta-introspector/text-split-explorer ./15/text-split-explorer
git submodule add https://github.com/ipfs/ipfs-update ./15/ipfs-update
git submodule add https://github.com/meta-introspector/Inspirationals ./15/Inspirationals
git submodule add https://github.com/actions/runner ./30/runner
git submodule add https://github.com/golangci/golangci-lint ./30/golangci-lint
git submodule add https://github.com/meta-introspector/compose-action ./30/compose-action
git submodule add https://github.com/meta-introspector/setup-python ./30/setup-python
git submodule add https://github.com/meta-introspector/act ./30/act
git submodule add https://github.com/moovweb/gvm ./30/gvm
git submodule add https://github.com/meta-introspector/act_base/ ./30/act_base
git submodule add https://github.com/Deadsg/BatsyDefenseAi ./13/BatsyDefenseAi
git submodule add https://github.com/streamlit/streamlit ./11/streamlit
git submodule add https://github.com/meta-introspector/streamlit-server-state ./11/streamlit-server-state
git submodule add https://github.com/whitphx/streamlit-webrtc ./11/streamlit-webrtc
git submodule add https://github.com/ParisNeo/lollms_bindings_zoo.git ./24/ai-ticket/vendor/lollms/zoos/bindings_zoo
git submodule add https://github.com/SilenNaihin/babyagi.git ./24/ai-ticket/vendor/babyagi
git submodule add https://github.com/meta-introspector/pyre-check ./24/ai-ticket/vendor/analysis/pyre-check
git submodule add https://github.com/MasonBoom/AutoGPT.git ./24/ai-ticket/vendor/MasonBoomPersonalAssistant
git submodule add https://github.com/polywrap/PolyGPT.git ./24/ai-ticket/vendor/PolyGPT
git submodule add https://github.com/gventuri/pandas-ai/ ./24/ai-ticket
git submodule add https://github.com/streamlit/streamlit-example ./06/streamlit-example
git submodule add https://github.com/meta-introspector/data/ ./06/streamlit-hackathon
git submodule add https://github.com/zzp-seeker/AutoGPT ./06/Auto-GPT
git submodule add https://github.com/AntonOsika/gpt-engineer ./29/gpt-engineer
git submodule add https://github.com/Clarifai/module-llm-battleground ./09/module-llm-battleground
git submodule add https://github.com/NVIDIA/NeMo ./16/NeMo
git submodule add https://github.com/LAION-AI/Open-Assistant ./16/Open-Assistant
git submodule add https://github.com/grill-lab/OAT ./16/OAT
git submodule add https://github.com/overgter/concrete-ml ./16/concrete-ml
git submodule add https://github.com/meta-introspector/gptlab-streamlit ./16/gptlab-streamlit
git submodule add https://github.com/RagingTiger/OmegaLurk ./16/OmegaLurk
git submodule add https://github.com/muonsoft/openapi-mock ./16/api_proxy
git submodule add https://github.com/mrk-andreev/tornado-swagger ./16/tornado-swagger
git submodule add https://github.com/PromtEngineer/localGPT ./16/localGPT
git submodule add https://github.com/SeldonIO/seldon-core ./16/seldon-core
git submodule add https://github.com/EdVince/Stable-Diffusion-NCNN ./16/LocalAI/go-stable-diffusion
git submodule add https://github.com/saharNooby/rwkv.cpp ./16/LocalAI/go-rwkv
git submodule add https://github.com/cmp-nct/ggllm.cpp ./16/LocalAI/go-ggllm
git submodule add https://github.com/ggerganov/whisper.spm ./16/LocalAI/whisper.cpp
git submodule add https://github.com/ggerganov/ggml ./16/LocalAI/go-ggml-transformers
git submodule add https://github.com/go-skynet/bloomz.cpp ./16/LocalAI/bloomz
git submodule add https://github.com/go-skynet/LocalAI ./16/LocalAI
git submodule add https://github.com/nomic-ai/llama.cpp.git ./16/LocalAI/gpt4all
git submodule add https://github.com/rhasspy/piper ./16/LocalAI/go-piper
git submodule add https://github.com/ggerganov/llama.cpp ./16/LocalAI/go-llama-stable
git submodule add https://github.com/skeskinen/bert.cpp ./16/LocalAI/go-bert
git submodule add https://github.com/ggerganov/llama.cpp ./16/LocalAI/go-llama
git submodule add https://github.com/juanluisbaptiste/docker-otrs ./23/docker-otrs
git submodule add https://github.com/doxygen/doxygen ./20/doxygen
git submodule add https://github.com/gravitee-io/gravitee-api-management ./20/gravitee-api-management
git submodule add https://github.com/jgm/pandoc ./20/pandoc
git submodule add https://github.com/cloudflare/workers-sdk ./20/workers-sdk
git submodule add https://github.com/mitmproxy/mitmproxy.git ./20/mitmproxy
git submodule add https://github.com/Helicone/helicone ./20/helicone
git submodule add https://github.com/meta-introspector/supabase ./20/supabase
git submodule add https://github.com/nalbion/auto-gpt-action ./25/auto-gpt-action
git submodule add https://github.com/peter-evans/create-or-update-comment ./25/create-or-update-comment
git submodule add https://github.com/meta-introspector/introspector-streamlit-agraph-component ./18/introspector-streamlit-agraph-component
git submodule add https://github.com/Deadsg/B.A.T.M.A.N ./18/B.A.T.M.A.N
git submodule add https://github.com/meta-introspector/streamlit-agraph ./18/streamlit-agraph
git submodule add https://github.com/bouzidanas/streamlit.io/ ./18/streamlit.io
git submodule add https://github.com/crubier/react-graph-vis ./18/react-graph-vis
git submodule add https://github.com/e2b-dev/e2b ./10/e2b
git submodule add https://github.com/vmagamedov/grpclib ./02/grpclib
git submodule add https://github.com/d5h-foss/grpc-interceptor ./02/grpc-interceptor
git submodule add https://github.com/grpc/grpc-haskell ./02/grpc-haskell
git submodule add https://github.com/marieai/marie-ai ./02/marie-ai
git submodule add https://github.com/madler/zlib ./02/gprc
git submodule add https://github.com/Em1tSan/NeuroGPT/ ./22/NeuroGPT
git submodule add https://github.com/bigscience-workshop/petals ./22/petals
git submodule add https://github.com/AndreyRGW/FreeGPT ./22/FreeGPT
git submodule add https://gist.github.com/kinoc/8a042d8c5683725aa8c372274c02ea2f ./22/open-ai-api
git submodule add https://github.com/xtekky/gpt4free ./22/gpt4free
git submodule add https://github.com/trotsky1997/Local-openai-server ./22/Local-openai-server
git submodule add https://github.com/Jirubizu/localai-admin ./22/localai-admin
git submodule add https://github.com/weekend-project-space/bootstrap-gpt ./22/bootstrap-gpt
git submodule add https://github.com/Dhruvgera/LocalAI-frontend ./21/LocalAI-frontend
git submodule add https://github.com/18870/chatgpt-proxy ./21/chatgpt-proxy-18870
git submodule add https://github.com/itsuka-dev/plurality ./21/plurality
git submodule add https://github.com/openai/openai-python ./21/openai-python
git submodule add https://github.com/PawanOsman/ChatGPT ./21/ChatGPT
git submodule add https://github.com/imyuanx/chatgpt-proxy ./21/chatgpt-proxy
git submodule add https://github.com/meta-introspector/model-gallery ./21/model-gallery
git submodule add https://github.com/TheR1D/shell_gpt ./21/shell_gpt
git submodule add https://github.com/jmikedupont2/go-ggllm.cpp ./21/go-ggllm.cpp
git submodule add https://github.com/cmp-nct/ggllm.cpp ./21/go-ggllm.cpp/go-ggllm.cpp
git submodule add https://github.com/acheong08/ChatGPTProxy ./21/ChatGPTProxy
git submodule add https://github.com/acheong08/ChatGPT-to-API ./21/ChatGPT-to-API
